"""Predefined hyperparameter search spaces for Optuna and Hyperopt."""

from __future__ import annotations

__all__ = ["SEARCH_SPACES"]

SEARCH_SPACES: dict = {
    "optuna": {
        "xgboost_classification": {
            "n_estimators": {"type": "int", "low": 100, "high": 1000},
            "max_depth": {"type": "int", "low": 3, "high": 9},
            "learning_rate": {"type": "float", "low": 0.01, "high": 0.3, "log": True},
            "subsample": {"type": "float", "low": 0.6, "high": 1.0},
            "colsample_bytree": {"type": "float", "low": 0.5, "high": 1.0},
            "reg_alpha": {"type": "float", "low": 1e-4, "high": 10.0, "log": True},
            "reg_lambda": {"type": "float", "low": 1e-4, "high": 10.0, "log": True},
            "min_child_weight": {"type": "int", "low": 1, "high": 20},
        },
        "logistic_classification": {
            "C": {"type": "float", "low": 1e-4, "high": 100.0, "log": True},
            "l1_ratio": {"type": "float", "low": 0.0, "high": 1.0},
        },
        "random_forest_classification": {
            "n_estimators": {"type": "int", "low": 50, "high": 500},
            "max_depth": {"type": "int", "low": 3, "high": 10},
            "min_samples_leaf": {"type": "int", "low": 5, "high": 50},
            "max_features": {"type": "float", "low": 0.3, "high": 1.0},
        },
        "svm_classification": {
            "C": {"type": "float", "low": 1e-3, "high": 100.0, "log": True},
            "kernel": {"type": "categorical", "choices": ["linear", "rbf", "poly"]},
            "gamma": {"type": "float", "low": 1e-4, "high": 1.0, "log": True},
        },
        "knn_classification": {
            "n_neighbors": {"type": "int", "low": 3, "high": 30},
            "weights": {"type": "categorical", "choices": ["uniform", "distance"]},
            "p": {"type": "int", "low": 1, "high": 2},
        },
        "decision_tree_classification": {
            "max_depth": {"type": "int", "low": 2, "high": 10},
            "min_samples_leaf": {"type": "int", "low": 5, "high": 50},
            "max_features": {"type": "float", "low": 0.3, "high": 1.0},
        },
        "extra_trees_classification": {
            "n_estimators": {"type": "int", "low": 50, "high": 500},
            "max_depth": {"type": "int", "low": 3, "high": 10},
            "min_samples_leaf": {"type": "int", "low": 5, "high": 50},
            "max_features": {"type": "float", "low": 0.3, "high": 1.0},
        },
        "adaboost_classification": {
            "n_estimators": {"type": "int", "low": 50, "high": 500},
            "learning_rate": {"type": "float", "low": 0.01, "high": 1.0, "log": True},
        },
        "naive_bayes_classification": {
            "var_smoothing": {"type": "float", "low": 1e-12, "high": 1e-6, "log": True},
        },
        "lightgbm_classification": {
            "n_estimators": {"type": "int", "low": 100, "high": 1000},
            "num_leaves": {"type": "int", "low": 15, "high": 255},
            "learning_rate": {"type": "float", "low": 0.01, "high": 0.3, "log": True},
            "subsample": {"type": "float", "low": 0.6, "high": 1.0},
            "colsample_bytree": {"type": "float", "low": 0.5, "high": 1.0},
            "reg_alpha": {"type": "float", "low": 1e-4, "high": 10.0, "log": True},
            "reg_lambda": {"type": "float", "low": 1e-4, "high": 10.0, "log": True},
            "min_child_samples": {"type": "int", "low": 5, "high": 100},
        },
        "gradient_boosting_classification": {
            "n_estimators": {"type": "int", "low": 50, "high": 500},
            "max_depth": {"type": "int", "low": 2, "high": 8},
            "learning_rate": {"type": "float", "low": 0.01, "high": 0.3, "log": True},
            "subsample": {"type": "float", "low": 0.6, "high": 1.0},
        },
        "xgboost_regression": {
            "n_estimators": {"type": "int", "low": 100, "high": 1000},
            "max_depth": {"type": "int", "low": 3, "high": 8},
            "learning_rate": {"type": "float", "low": 0.01, "high": 0.3, "log": True},
            "subsample": {"type": "float", "low": 0.6, "high": 1.0},
            "colsample_bytree": {"type": "float", "low": 0.5, "high": 1.0},
            "reg_alpha": {"type": "float", "low": 1e-4, "high": 10.0, "log": True},
            "reg_lambda": {"type": "float", "low": 1e-4, "high": 10.0, "log": True},
        },
        "ridge_regression": {
            "alpha": {"type": "float", "low": 1e-3, "high": 1000.0, "log": True},
        },
        "elastic_net_regression": {
            "alpha": {"type": "float", "low": 1e-3, "high": 1000.0, "log": True},
            "l1_ratio": {"type": "float", "low": 0.0, "high": 1.0},
        },
        "gradient_boosting_regression": {
            "n_estimators": {"type": "int", "low": 50, "high": 500},
            "max_depth": {"type": "int", "low": 2, "high": 8},
            "learning_rate": {"type": "float", "low": 0.01, "high": 0.3, "log": True},
            "subsample": {"type": "float", "low": 0.6, "high": 1.0},
        },
        "svm_regression": {
            "C": {"type": "float", "low": 1e-3, "high": 100.0, "log": True},
            "kernel": {"type": "categorical", "choices": ["linear", "rbf", "poly"]},
            "gamma": {"type": "float", "low": 1e-4, "high": 1.0, "log": True},
            "epsilon": {"type": "float", "low": 1e-3, "high": 1.0, "log": True},
        },
        "knn_regression": {
            "n_neighbors": {"type": "int", "low": 3, "high": 30},
            "weights": {"type": "categorical", "choices": ["uniform", "distance"]},
            "p": {"type": "int", "low": 1, "high": 2},
        },
        "decision_tree_regression": {
            "max_depth": {"type": "int", "low": 2, "high": 10},
            "min_samples_leaf": {"type": "int", "low": 5, "high": 50},
            "max_features": {"type": "float", "low": 0.3, "high": 1.0},
        },
        "extra_trees_regression": {
            "n_estimators": {"type": "int", "low": 50, "high": 500},
            "max_depth": {"type": "int", "low": 3, "high": 10},
            "min_samples_leaf": {"type": "int", "low": 5, "high": 50},
            "max_features": {"type": "float", "low": 0.3, "high": 1.0},
        },
        "adaboost_regression": {
            "n_estimators": {"type": "int", "low": 50, "high": 500},
            "learning_rate": {"type": "float", "low": 0.01, "high": 1.0, "log": True},
        },
        "lightgbm_regression": {
            "n_estimators": {"type": "int", "low": 100, "high": 1000},
            "num_leaves": {"type": "int", "low": 15, "high": 255},
            "learning_rate": {"type": "float", "low": 0.01, "high": 0.3, "log": True},
            "subsample": {"type": "float", "low": 0.6, "high": 1.0},
            "colsample_bytree": {"type": "float", "low": 0.5, "high": 1.0},
            "reg_alpha": {"type": "float", "low": 1e-4, "high": 10.0, "log": True},
            "reg_lambda": {"type": "float", "low": 1e-4, "high": 10.0, "log": True},
            "min_child_samples": {"type": "int", "low": 5, "high": 100},
        },
        "random_forest_regression": {
            "n_estimators": {"type": "int", "low": 50, "high": 500},
            "max_depth": {"type": "int", "low": 3, "high": 10},
            "min_samples_leaf": {"type": "int", "low": 5, "high": 50},
            "max_features": {"type": "float", "low": 0.3, "high": 1.0},
        },
        "lasso_regression": {
            "alpha": {"type": "float", "low": 1e-3, "high": 1000.0, "log": True},
        },
    },
    "hyperopt": {
        "xgboost_classification": {
            "n_estimators": {"type": "quniform", "low": 100, "high": 1000, "q": 10},
            "max_depth": {"type": "quniform", "low": 3, "high": 9, "q": 1},
            "learning_rate": {"type": "loguniform", "low": 0.01, "high": 0.3},
            "subsample": {"type": "uniform", "low": 0.6, "high": 1.0},
            "colsample_bytree": {"type": "uniform", "low": 0.5, "high": 1.0},
            "reg_alpha": {"type": "loguniform", "low": 1e-4, "high": 10.0},
            "reg_lambda": {"type": "loguniform", "low": 1e-4, "high": 10.0},
            "min_child_weight": {"type": "quniform", "low": 1, "high": 20, "q": 1},
        },
        "logistic_classification": {
            "C": {"type": "loguniform", "low": 1e-4, "high": 100.0},
        },
        "svm_classification": {
            "C": {"type": "loguniform", "low": 1e-3, "high": 100.0},
            "kernel": {"type": "categorical", "choices": ["linear", "rbf", "poly"]},
            "gamma": {"type": "loguniform", "low": 1e-4, "high": 1.0},
        },
        "knn_classification": {
            "n_neighbors": {"type": "quniform", "low": 3, "high": 30, "q": 1},
            "weights": {"type": "categorical", "choices": ["uniform", "distance"]},
            "p": {"type": "quniform", "low": 1, "high": 2, "q": 1},
        },
        "decision_tree_classification": {
            "max_depth": {"type": "quniform", "low": 2, "high": 10, "q": 1},
            "min_samples_leaf": {"type": "quniform", "low": 5, "high": 50, "q": 1},
            "max_features": {"type": "uniform", "low": 0.3, "high": 1.0},
        },
        "random_forest_classification": {
            "n_estimators": {"type": "quniform", "low": 50, "high": 500, "q": 10},
            "max_depth": {"type": "quniform", "low": 3, "high": 10, "q": 1},
            "min_samples_leaf": {"type": "quniform", "low": 5, "high": 50, "q": 1},
            "max_features": {"type": "uniform", "low": 0.3, "high": 1.0},
        },
        "extra_trees_classification": {
            "n_estimators": {"type": "quniform", "low": 50, "high": 500, "q": 10},
            "max_depth": {"type": "quniform", "low": 3, "high": 10, "q": 1},
            "min_samples_leaf": {"type": "quniform", "low": 5, "high": 50, "q": 1},
            "max_features": {"type": "uniform", "low": 0.3, "high": 1.0},
        },
        "adaboost_classification": {
            "n_estimators": {"type": "quniform", "low": 50, "high": 500, "q": 10},
            "learning_rate": {"type": "loguniform", "low": 0.01, "high": 1.0},
        },
        "naive_bayes_classification": {
            "var_smoothing": {"type": "loguniform", "low": 1e-12, "high": 1e-6},
        },
        "lightgbm_classification": {
            "n_estimators": {"type": "quniform", "low": 100, "high": 1000, "q": 10},
            "num_leaves": {"type": "quniform", "low": 15, "high": 255, "q": 1},
            "learning_rate": {"type": "loguniform", "low": 0.01, "high": 0.3},
            "subsample": {"type": "uniform", "low": 0.6, "high": 1.0},
            "colsample_bytree": {"type": "uniform", "low": 0.5, "high": 1.0},
            "reg_alpha": {"type": "loguniform", "low": 1e-4, "high": 10.0},
            "reg_lambda": {"type": "loguniform", "low": 1e-4, "high": 10.0},
            "min_child_samples": {"type": "quniform", "low": 5, "high": 100, "q": 1},
        },
        "gradient_boosting_classification": {
            "n_estimators": {"type": "quniform", "low": 50, "high": 500, "q": 10},
            "max_depth": {"type": "quniform", "low": 2, "high": 8, "q": 1},
            "learning_rate": {"type": "loguniform", "low": 0.01, "high": 0.3},
            "subsample": {"type": "uniform", "low": 0.6, "high": 1.0},
        },
        "xgboost_regression": {
            "n_estimators": {"type": "quniform", "low": 100, "high": 1000, "q": 10},
            "max_depth": {"type": "quniform", "low": 3, "high": 8, "q": 1},
            "learning_rate": {"type": "loguniform", "low": 0.01, "high": 0.3},
            "subsample": {"type": "uniform", "low": 0.6, "high": 1.0},
            "colsample_bytree": {"type": "uniform", "low": 0.5, "high": 1.0},
        },
        "ridge_regression": {
            "alpha": {"type": "loguniform", "low": 1e-3, "high": 1000.0},
        },
        "elastic_net_regression": {
            "alpha": {"type": "loguniform", "low": 1e-3, "high": 1000.0},
            "l1_ratio": {"type": "uniform", "low": 0.0, "high": 1.0},
        },
        "gradient_boosting_regression": {
            "n_estimators": {"type": "quniform", "low": 50, "high": 500, "q": 10},
            "max_depth": {"type": "quniform", "low": 2, "high": 8, "q": 1},
            "learning_rate": {"type": "loguniform", "low": 0.01, "high": 0.3},
            "subsample": {"type": "uniform", "low": 0.6, "high": 1.0},
        },
        "svm_regression": {
            "C": {"type": "loguniform", "low": 1e-3, "high": 100.0},
            "kernel": {"type": "categorical", "choices": ["linear", "rbf", "poly"]},
            "gamma": {"type": "loguniform", "low": 1e-4, "high": 1.0},
            "epsilon": {"type": "loguniform", "low": 1e-3, "high": 1.0},
        },
        "knn_regression": {
            "n_neighbors": {"type": "quniform", "low": 3, "high": 30, "q": 1},
            "weights": {"type": "categorical", "choices": ["uniform", "distance"]},
            "p": {"type": "quniform", "low": 1, "high": 2, "q": 1},
        },
        "decision_tree_regression": {
            "max_depth": {"type": "quniform", "low": 2, "high": 10, "q": 1},
            "min_samples_leaf": {"type": "quniform", "low": 5, "high": 50, "q": 1},
            "max_features": {"type": "uniform", "low": 0.3, "high": 1.0},
        },
        "extra_trees_regression": {
            "n_estimators": {"type": "quniform", "low": 50, "high": 500, "q": 10},
            "max_depth": {"type": "quniform", "low": 3, "high": 10, "q": 1},
            "min_samples_leaf": {"type": "quniform", "low": 5, "high": 50, "q": 1},
            "max_features": {"type": "uniform", "low": 0.3, "high": 1.0},
        },
        "adaboost_regression": {
            "n_estimators": {"type": "quniform", "low": 50, "high": 500, "q": 10},
            "learning_rate": {"type": "loguniform", "low": 0.01, "high": 1.0},
        },
        "lightgbm_regression": {
            "n_estimators": {"type": "quniform", "low": 100, "high": 1000, "q": 10},
            "num_leaves": {"type": "quniform", "low": 15, "high": 255, "q": 1},
            "learning_rate": {"type": "loguniform", "low": 0.01, "high": 0.3},
            "subsample": {"type": "uniform", "low": 0.6, "high": 1.0},
            "colsample_bytree": {"type": "uniform", "low": 0.5, "high": 1.0},
            "reg_alpha": {"type": "loguniform", "low": 1e-4, "high": 10.0},
            "reg_lambda": {"type": "loguniform", "low": 1e-4, "high": 10.0},
            "min_child_samples": {"type": "quniform", "low": 5, "high": 100, "q": 1},
        },
        "random_forest_regression": {
            "n_estimators": {"type": "quniform", "low": 50, "high": 500, "q": 10},
            "max_depth": {"type": "quniform", "low": 3, "high": 10, "q": 1},
            "min_samples_leaf": {"type": "quniform", "low": 5, "high": 50, "q": 1},
            "max_features": {"type": "uniform", "low": 0.3, "high": 1.0},
        },
        "lasso_regression": {
            "alpha": {"type": "loguniform", "low": 1e-3, "high": 1000.0},
        },
    },
}

# Medians / defaults used by backend="predefined"
PREDEFINED_PARAMS: dict = {
    "xgboost_classification": {
        "n_estimators": 300,
        "max_depth": 6,
        "learning_rate": 0.05,
        "subsample": 0.8,
        "colsample_bytree": 0.8,
        "reg_alpha": 0.1,
        "reg_lambda": 1.0,
        "min_child_weight": 5,
    },
    "logistic_classification": {"C": 1.0, "l1_ratio": 0.0},
    "random_forest_classification": {
        "n_estimators": 200,
        "max_depth": 8,
        "min_samples_leaf": 20,
        "max_features": 0.7,
    },
    "svm_classification": {"C": 1.0, "kernel": "rbf", "gamma": 0.01},
    "knn_classification": {"n_neighbors": 5, "weights": "uniform", "p": 2},
    "decision_tree_classification": {"max_depth": 6, "min_samples_leaf": 20, "max_features": 0.7},
    "extra_trees_classification": {
        "n_estimators": 200,
        "max_depth": 8,
        "min_samples_leaf": 20,
        "max_features": 0.7,
    },
    "adaboost_classification": {"n_estimators": 100, "learning_rate": 0.1},
    "naive_bayes_classification": {"var_smoothing": 1e-9},
    "lightgbm_classification": {
        "n_estimators": 300,
        "num_leaves": 63,
        "learning_rate": 0.05,
        "subsample": 0.8,
        "colsample_bytree": 0.8,
        "reg_alpha": 0.1,
        "reg_lambda": 1.0,
        "min_child_samples": 20,
    },
    "gradient_boosting_classification": {
        "n_estimators": 200,
        "max_depth": 4,
        "learning_rate": 0.05,
        "subsample": 0.8,
    },
    "xgboost_regression": {
        "n_estimators": 300,
        "max_depth": 5,
        "learning_rate": 0.05,
        "subsample": 0.8,
        "colsample_bytree": 0.8,
    },
    "ridge_regression": {"alpha": 1.0},
    "elastic_net_regression": {"alpha": 1.0, "l1_ratio": 0.5},
    "gradient_boosting_regression": {
        "n_estimators": 200,
        "max_depth": 4,
        "learning_rate": 0.05,
        "subsample": 0.8,
    },
    "svm_regression": {"C": 1.0, "kernel": "rbf", "gamma": 0.01, "epsilon": 0.1},
    "knn_regression": {"n_neighbors": 5, "weights": "uniform", "p": 2},
    "decision_tree_regression": {"max_depth": 6, "min_samples_leaf": 20, "max_features": 0.7},
    "extra_trees_regression": {
        "n_estimators": 200,
        "max_depth": 8,
        "min_samples_leaf": 20,
        "max_features": 0.7,
    },
    "adaboost_regression": {"n_estimators": 100, "learning_rate": 0.1},
    "lightgbm_regression": {
        "n_estimators": 300,
        "num_leaves": 63,
        "learning_rate": 0.05,
        "subsample": 0.8,
        "colsample_bytree": 0.8,
        "reg_alpha": 0.1,
        "reg_lambda": 1.0,
        "min_child_samples": 20,
    },
    "random_forest_regression": {
        "n_estimators": 200,
        "max_depth": 8,
        "min_samples_leaf": 20,
        "max_features": 0.7,
    },
    "lasso_regression": {"alpha": 1.0},
}
