"""RunStateStore: server-side per-run_id state, keyed the same way session_state is in
dscompanion/app/interactive_state.py — but living in dscompanion/api/, never in the browser.

Backend selection mirrors dscompanion/dscompanion/tuning/tuner.py's Tuner.backend pattern: a plain
string setting plus a lazy import per branch — no abstract base class, no plugin registry.
"""

from __future__ import annotations

import logging
import threading
import uuid
from dataclasses import dataclass, field
from typing import Any

from dscompanion.api.steps import STEP_ORDER, StepId, steps_from

logger = logging.getLogger(__name__)

__all__ = ["RunState", "JobState", "RunStateStore", "get_run_state_store"]


@dataclass
class RunState:
    """All server-side state for one run_id — the REST equivalent of one Streamlit session's
    ``interactive.*``/``int.stepN.*`` session-state keys.

    Args:
        run_id (str): Unique identifier for this run, generated by
            ``RunStateStore.create_run()``.

    Attributes:
        step_confirmed (dict[StepId, bool]): One entry per step slug — the REST
            equivalent of ``interactive.step{N}_confirmed``. All ``False`` at creation.
        step_status (dict[StepId, str]): One of ``"done"``, ``"current"``, ``"pending"``,
            ``"flagged"`` per step — mirrors ``interactive.step_status``.
        step_data (dict[StepId, dict]): Confirmed payload per step (the fields a later
            step or the frontend needs), keyed by step slug. Only populated once a
            step's `/confirm` endpoint has been called.
        audit_trail (list[tuple[StepId, str]]): One plain-language entry per confirmed
            step, same shape as ``interactive.audit_trail``.
        artifacts (dict[str, Any]): Fitted dscompanion objects too large/unserialisable for
            `step_data` (e.g. `DataSplit`, `FeatureProcessingPipeline`, a trained
            model) — kept server-side only, never serialised into an API response.
        jobs (dict[str, JobState]): Background job state (Step 8 leaderboard, Step 9
            tuning), keyed by `job_id`.
    """

    run_id: str
    step_confirmed: dict[StepId, bool] = field(
        default_factory=lambda: {step: False for step in STEP_ORDER}
    )
    step_status: dict[StepId, str] = field(
        default_factory=lambda: {
            step: ("current" if step == STEP_ORDER[0] else "pending") for step in STEP_ORDER
        }
    )
    step_data: dict[StepId, dict] = field(default_factory=dict)
    audit_trail: list[tuple[StepId, str]] = field(default_factory=list)
    artifacts: dict[str, Any] = field(default_factory=dict)
    jobs: dict[str, "JobState"] = field(default_factory=dict)

    def reset_from_step(self, step: StepId) -> None:
        """Invalidate ``step`` and every step after it — the REST equivalent of
        ``dscompanion/app/interactive_state.py``'s ``reset_from_step()``.

        Args:
            step (StepId): The first step slug to invalidate. This step and every
                step after it (per ``STEP_ORDER``) is reset.

        Returns:
            None
        """
        reset_steps = steps_from(step)
        for s in reset_steps:
            self.step_confirmed[s] = False
            self.step_status[s] = "pending"
            self.step_data.pop(s, None)
        reset_set = set(reset_steps)
        self.audit_trail = [(s, text) for s, text in self.audit_trail if s not in reset_set]
        logger.info("run_id=%s reset from step %s onward", self.run_id, step)


@dataclass
class JobState:
    """State for one background job (Step 8 leaderboard training, Step 9 tuning) —
    the REST equivalent of Step 8's ``int.step8.lb_progress``/``lb_running`` session
    -state keys, generalised to also cover Step 9's currently-synchronous ``Tuner.run()``
    — a REST client can't hold an HTTP connection open through a multi-minute
    Optuna run the way a Streamlit tab's spinner can.

    Args:
        job_id (str): Unique identifier, generated by ``RunStateStore.create_job()``.
        step (StepId): Which wizard step this job belongs to (``"train"`` or
            ``"tuning"`` today).

    Attributes:
        status (str): One of ``"running"``, ``"done"``, ``"error"``.
        progress (list[dict]): Incremental progress entries, appended to under
            ``lock`` — same shape as Step 8's existing ``{"algorithm", "status",
            "detail"}`` dicts.
        result (dict | None): Final result payload once ``status != "running"``.
        error (str | None): Error message if ``status == "error"``.
        lock (threading.Lock): Guards ``progress`` against concurrent read (API poll)
            and write (the background thread) — same pattern already proven in
            ``dscompanion/app/interactive_step8.py``'s ``_leaderboard_worker``.
    """

    job_id: str
    step: StepId
    status: str = "running"
    progress: list[dict] = field(default_factory=list)
    result: dict | None = None
    error: str | None = None
    lock: threading.Lock = field(default_factory=threading.Lock)


class RunStateStore:
    """In-memory ``RunState`` store keyed by ``run_id``.

    Audit-trail durability (does state need to survive an API restart?) is an
    explicit open decision, not resolved by this
    class; it starts as a plain in-memory dict on purpose, matching
    `APISettings.state_backend`'s default. A `"redis"` (or Lakebase-backed, per the
    Databricks Apps research in `frontend.md`) backend would be a second branch
    here, not a rewrite — same dispatch idiom as `Tuner.backend`.

    Attributes:
        None (all state lives in the private ``_runs``/``_lock`` below).
    """

    def __init__(self) -> None:
        self._runs: dict[str, RunState] = {}
        self._lock = threading.Lock()

    def create_run(self) -> RunState:
        """Creates a new, empty ``RunState`` and stores it.

        Args:
            None

        Returns:
            RunState: The newly created state, with a fresh ``run_id``.
        """
        run_id = str(uuid.uuid4())
        state = RunState(run_id=run_id)
        with self._lock:
            self._runs[run_id] = state
        logger.info("Created run_id=%s", run_id)
        return state

    def get_run(self, run_id: str) -> RunState:
        """Fetches the ``RunState`` for ``run_id``.

        Args:
            run_id (str): The run identifier returned by ``create_run()``.

        Returns:
            RunState: The stored state for this run.

        Raises:
            KeyError: If ``run_id`` is not known to this store.
        """
        with self._lock:
            if run_id not in self._runs:
                raise KeyError(f"Unknown run_id: {run_id!r}")
            return self._runs[run_id]

    def create_job(self, run_id: str, step: StepId) -> JobState:
        """Creates a new background job under ``run_id``.

        Args:
            run_id (str): The run this job belongs to.
            step (StepId): Which wizard step (``"train"`` or ``"tuning"``) started
                this job.

        Returns:
            JobState: The newly created job state, with a fresh ``job_id``.

        Raises:
            KeyError: If ``run_id`` is not known to this store.
        """
        run = self.get_run(run_id)
        job_id = str(uuid.uuid4())
        job = JobState(job_id=job_id, step=step)
        run.jobs[job_id] = job
        logger.info("run_id=%s created job_id=%s for step=%s", run_id, job_id, step)
        return job

    def get_job(self, run_id: str, job_id: str) -> JobState:
        """Fetches a job's state.

        Args:
            run_id (str): The run this job belongs to.
            job_id (str): The job identifier returned by ``create_job()``.

        Returns:
            JobState: The stored job state.

        Raises:
            KeyError: If ``run_id`` or ``job_id`` is not known to this store.
        """
        run = self.get_run(run_id)
        if job_id not in run.jobs:
            raise KeyError(f"Unknown job_id: {job_id!r} for run_id: {run_id!r}")
        return run.jobs[job_id]


_store: RunStateStore | None = None


def get_run_state_store() -> RunStateStore:
    """Returns the process-wide ``RunStateStore`` singleton, dispatched by
    ``api_settings.state_backend`` exactly like ``Tuner.backend`` dispatches to
    ``OptunaBackend``/``HyperoptBackend``.

    Args:
        None

    Returns:
        RunStateStore: The active store instance.

    Raises:
        ValueError: If ``api_settings.state_backend`` is not a recognised value.
    """
    global _store
    if _store is not None:
        return _store

    from dscompanion.api.config import api_settings

    if api_settings.state_backend == "memory":
        _store = RunStateStore()
    elif api_settings.state_backend == "redis":
        raise NotImplementedError(
            "state_backend='redis' is not built yet. "
            "Use 'memory' (the default) until this channel is actually pursued."
        )
    else:
        raise ValueError(
            f"Unknown state_backend: {api_settings.state_backend!r}. Choose memory/redis."
        )
    return _store
