"""EDA report: public API that orchestrates all EDA analysers."""

from __future__ import annotations

import logging
import tempfile
from pathlib import Path
from typing import Any

import pandas as pd
import plotly.graph_objects as go

logger = logging.getLogger(__name__)

from dscompanion.config import settings
from dscompanion.eda.bivariate import BivariateAnalyser
from dscompanion.eda.missingness import MissingnessAnalyser
from dscompanion.eda.multivariate import MultivariateAnalyser
from dscompanion.eda.univariate import UnivariateAnalyser
from dscompanion.utils.plotting import apply_dscompanion_theme
from dscompanion.utils.validators import is_databricks

__all__ = ["EDAReport", "EDAAlert"]


class EDAAlert:
    """Namespace of alert-type string constants produced by ``EDAReport.alerts()``.

    Centralising these as constants (rather than inline string literals)
    keeps ``EDAReport.alerts()`` and any consumer (e.g. ``ModelCard``'s badge
    colour map) in sync — a typo in either place becomes an import error
    instead of a silently-unmatched badge.
    """

    HIGH_MISSING = "HIGH_MISSING"
    CONSTANT = "CONSTANT"
    NEAR_ZERO_VARIANCE = "NEAR_ZERO_VARIANCE"
    HIGH_CARDINALITY = "HIGH_CARDINALITY"
    SKEWED = "SKEWED"
    ZEROS = "ZEROS"
    LOW_IV = "LOW_IV"
    MULTICOLLINEAR = "MULTICOLLINEAR"
    HIGH_CORRELATION = "HIGH_CORRELATION"
    IMBALANCED = "IMBALANCED"


_HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><title>{{ title }}</title>
<style>
body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;margin:0;
padding:20px;background:#f5f7fa;color:#222}
h1,h2{color:#1a2a4a}
table{border-collapse:collapse;width:100%;font-size:13px}
th{background:#f0f2f6;padding:6px 10px;text-align:left}
td{padding:5px 10px;border-bottom:1px solid #f0f2f6}
.card{background:#fff;border-radius:8px;padding:16px;margin-bottom:20px;
box-shadow:0 1px 4px rgba(0,0,0,.08)}
.flag-high{color:#c0392b;font-weight:600}.flag-med{color:#e67e22}
</style></head>
<body>
<h1>{{ title }}</h1>
<div class="card"><h2>Dataset Overview</h2>
<table><thead><tr><th>Metric</th><th>Value</th></tr></thead><tbody>
{% for k,v in overview.items() %}<tr><td>{{k}}</td><td>{{v}}</td></tr>{% endfor %}
</tbody></table></div>

<div class="card"><h2>Numeric Summary</h2>
<table><thead><tr>{% for col in num_cols %}<th>{{col}}</th>{% endfor %}</tr></thead>
<tbody>
{% for row in num_rows %}<tr>{% for v in row %}<td>{{v}}</td>{% endfor %}</tr>{% endfor %}
</tbody>
</table></div>

<div class="card"><h2>IV Table (sorted by IV)</h2>
<table><thead><tr><th>Feature</th><th>IV</th><th>Power</th></tr></thead><tbody>
{% for r in iv_rows %}<tr><td>{{r.feature}}</td>
<td class="{% if r.iv > 0.3 %}flag-high{% elif r.iv > 0.1 %}flag-med{% endif %}">{{r.iv}}</td>
<td>{{r.predictive_power}}</td></tr>{% endfor %}
</tbody></table></div>

<div class="card"><h2>Flagged Features</h2>
<table><thead><tr><th>Feature</th><th>Issue</th></tr></thead><tbody>
{% for r in flagged_rows %}
<tr><td>{{r.feature}}</td><td class="flag-high">{{r.issue}}</td></tr>
{% endfor %}
</tbody></table></div>
<p style="color:#aaa;font-size:11px;margin-top:40px">Generated by dscompanion EDAReport</p>
</body></html>"""


class EDAReport:
    """Orchestrate univariate, bivariate, and multivariate EDA analysers and expose a
    unified reporting API.

    Acts as a facade over ``UnivariateAnalyser``, ``BivariateAnalyser``, and
    ``MultivariateAnalyser``.  Calling ``run_all`` fits each analyser in
    sequence on the provided DataSplit and stores the fitted objects internally.
    Subsequent methods delegate to those objects to produce HTML reports,
    Databricks notebook displays, feature-flag dictionaries, and drop
    recommendations.  No side-effects outside this instance; does not mutate
    the DataSplit.

    Args:
        split: A ``DataSplit`` instance that exposes ``train_X``
            (``pandas.DataFrame``), ``train_y`` (``pandas.Series``), and a
            ``metadata`` object with a ``strategy`` attribute.
        target (str): Name of the target column.  Used as a label in the
            HTML report overview section and must correspond to the binary
            target variable used during DataSplit construction.
        high_missing_threshold (float): Missing-value rate above which
            ``alerts()`` raises a ``HIGH_MISSING`` alert for a feature.  A
            value of ``0`` delegates to ``settings.high_missing_threshold``.
        near_zero_variance_threshold (float): Variance below which a numeric
            feature is flagged ``near_zero_variance_flag`` (and, via
            ``recommended_drops``/``recommended_drops_with_reasons``,
            suggested for removal).  A value of ``0`` delegates to
            ``settings.near_zero_variance_threshold``.
        skewness_alert_threshold (float): Absolute skewness at-or-above
            which ``alerts()`` raises a ``SKEWED`` alert for a numeric
            feature.  A value of ``0`` delegates to
            ``settings.eda_skewness_alert_threshold``.
        zero_pct_alert_threshold (float): Zero-value rate at-or-above which
            ``alerts()`` raises a ``ZEROS`` alert for a numeric feature.  A
            value of ``0`` delegates to ``settings.eda_zero_pct_alert_threshold``.
        imbalance_alert_threshold (float): Entropy-based imbalance score
            at-or-above which ``alerts()`` raises an ``IMBALANCED`` alert
            for a categorical feature.  A value of ``0`` delegates to
            ``settings.eda_imbalance_alert_threshold``.
        extreme_values_n (int): Number of smallest/largest raw values
            captured per numeric feature by ``extreme_values()``.  A value
            of ``0`` delegates to ``settings.eda_extreme_values_n``.
        sample_n_rows (int): Rows shown per head/tail by ``sample_rows()``.
            A value of ``0`` delegates to ``settings.eda_sample_n_rows``.
        duplicate_rows_max_display (int): Cap on rows returned by
            ``duplicate_row_content()``.  A value of ``0`` delegates to
            ``settings.eda_duplicate_rows_max_display``.
        missing_matrix_max_rows (int): Row subsample cap for
            ``missing_matrix()``.  A value of ``0`` delegates to
            ``settings.eda_missing_matrix_max_rows``.
        interaction_max_numeric_cols (int): Cap on numeric columns
            considered by ``interaction_plots()``.  A value of ``0``
            delegates to ``settings.eda_interaction_max_numeric_cols``.
        interaction_hexbin_row_threshold (int): Row count above which
            ``interaction_plots()`` switches from scatter to hexbin.  A
            value of ``0`` delegates to
            ``settings.eda_interaction_hexbin_row_threshold``.
        text_analysis_top_n_words (int): Top-N word-frequency entries
            captured by ``word_frequency()``.  A value of ``0`` delegates to
            ``settings.eda_text_analysis_top_n_words``.
        text_analysis_top_n_chars (int): Top-N character-frequency entries
            captured by ``character_frequency()``.  A value of ``0``
            delegates to ``settings.eda_text_analysis_top_n_chars``.
        include_sample_rows (bool): Compliance opt-in for ``sample_rows()``
            output.  Defaults to ``False``.
        include_duplicate_row_content (bool): Compliance opt-in for
            ``duplicate_row_content()`` output.  Defaults to ``False``.
        include_text_sample_values (bool): Compliance opt-in for raw
            sample-value exposure in ``word_frequency()``/
            ``character_frequency()`` output.  Defaults to ``False``.

    Example::

        report = EDAReport(split, target="default_flag").run_all()
        report.to_html("eda.html")
        print(report.recommended_drops)
    """

    def __init__(
        self,
        split: Any,
        target: str,
        high_missing_threshold: float = 0.0,
        near_zero_variance_threshold: float = 0.0,
        skewness_alert_threshold: float = 0.0,
        zero_pct_alert_threshold: float = 0.0,
        imbalance_alert_threshold: float = 0.0,
        extreme_values_n: int = 0,
        sample_n_rows: int = 0,
        duplicate_rows_max_display: int = 0,
        missing_matrix_max_rows: int = 0,
        interaction_max_numeric_cols: int = 0,
        interaction_hexbin_row_threshold: int = 0,
        text_analysis_top_n_words: int = 0,
        text_analysis_top_n_chars: int = 0,
        include_sample_rows: bool = False,
        include_duplicate_row_content: bool = False,
        include_text_sample_values: bool = False,
    ) -> None:  # Any: DataSplit — avoids circular import
        self._split = split
        self._target = target
        self._high_missing_threshold = high_missing_threshold or settings.high_missing_threshold
        self._near_zero_variance_threshold = (
            near_zero_variance_threshold or settings.near_zero_variance_threshold
        )
        self._skewness_alert_threshold = (
            skewness_alert_threshold or settings.eda_skewness_alert_threshold
        )
        self._zero_pct_alert_threshold = (
            zero_pct_alert_threshold or settings.eda_zero_pct_alert_threshold
        )
        self._imbalance_alert_threshold = (
            imbalance_alert_threshold or settings.eda_imbalance_alert_threshold
        )
        self._extreme_values_n = extreme_values_n or settings.eda_extreme_values_n
        self._sample_n_rows = sample_n_rows or settings.eda_sample_n_rows
        self._duplicate_rows_max_display = (
            duplicate_rows_max_display or settings.eda_duplicate_rows_max_display
        )
        self._missing_matrix_max_rows = (
            missing_matrix_max_rows or settings.eda_missing_matrix_max_rows
        )
        self._interaction_max_numeric_cols = (
            interaction_max_numeric_cols or settings.eda_interaction_max_numeric_cols
        )
        self._interaction_hexbin_row_threshold = (
            interaction_hexbin_row_threshold or settings.eda_interaction_hexbin_row_threshold
        )
        self._text_analysis_top_n_words = (
            text_analysis_top_n_words or settings.eda_text_analysis_top_n_words
        )
        self._text_analysis_top_n_chars = (
            text_analysis_top_n_chars or settings.eda_text_analysis_top_n_chars
        )
        self._include_sample_rows = include_sample_rows
        self._include_duplicate_row_content = include_duplicate_row_content
        self._include_text_sample_values = include_text_sample_values
        self._uni: UnivariateAnalyser | None = None
        self._bi: BivariateAnalyser | None = None
        self._multi: MultivariateAnalyser | None = None
        self._missing: MissingnessAnalyser | None = None

    def run_all(self) -> "EDAReport":
        """Fit univariate, bivariate, and multivariate analysers in sequence on the
        stored DataSplit.

        Instantiates a fresh ``UnivariateAnalyser``, ``BivariateAnalyser``,
        and ``MultivariateAnalyser``, calling ``fit(self._split)`` on each in
        order.  Logs INFO messages at the start of each stage and on
        completion.  After this method returns, all accessor methods and
        properties on this instance become available.

        Args:
            None

        Returns:
            EDAReport: This instance, allowing method chaining
            (e.g. ``EDAReport(split, "target").run_all().to_html("out.html")``).
        """
        logger.info("EDAReport.run_all — starting univariate")
        self._uni = UnivariateAnalyser(
            high_missing_threshold=self._high_missing_threshold,
            near_zero_variance_threshold=self._near_zero_variance_threshold,
        ).fit(self._split)

        logger.info("EDAReport.run_all — bivariate")
        self._bi = BivariateAnalyser(
            interaction_max_numeric_cols=self._interaction_max_numeric_cols,
            interaction_hexbin_row_threshold=self._interaction_hexbin_row_threshold,
        ).fit(self._split)

        logger.info("EDAReport.run_all — multivariate")
        self._multi = MultivariateAnalyser().fit(self._split)

        logger.info("EDAReport.run_all — missingness")
        self._missing = MissingnessAnalyser(max_rows=self._missing_matrix_max_rows).fit(self._split)

        logger.info("EDAReport.run_all — complete")
        return self

    def to_html(self, path: str | Path) -> Path:
        """Render the complete EDA report to a self-contained HTML file and return its
        resolved path.

        Builds a Jinja2 template context from the numeric summary, IV table,
        and data quality flags, then writes a single UTF-8 encoded HTML file
        to the specified path.  The file can be opened directly in a browser
        with no external dependencies.  Parent directories must already exist;
        this method does not create them.  Logs an INFO message with the
        resolved path after writing.

        Args:
            path (str | pathlib.Path): Destination file path.  Relative paths
                are resolved relative to the current working directory.
                Existing files at this path are silently overwritten.

        Returns:
            pathlib.Path: The resolved (absolute) ``Path`` object of the
            written HTML file.

        Raises:
            RuntimeError: If ``run_all`` has not been called yet.
        """
        self._check_run()
        path = Path(path)

        num_df = self._uni.numeric_summary()
        iv_df = self._bi.iv_table()
        issues = self._uni.flag_issues()

        flagged_rows = []
        for _, row in issues.iterrows():
            for issue in ["high_missing", "near_zero_variance", "high_cardinality", "constant"]:
                if row.get(issue):
                    flagged_rows.append(
                        {"feature": row["feature"], "issue": issue.replace("_", " ")}
                    )

        overview = {
            "Train rows": f"{len(self._split.train_X):,}",
            "Columns": len(self._split.train_X.columns),
            "Target": self._target,
            "Strategy": self._split.metadata.strategy,
        }

        num_cols = num_df.columns.tolist() if len(num_df) > 0 else []
        num_rows = [row.tolist() for _, row in num_df.iterrows()]

        from jinja2 import Template

        html = Template(_HTML_TEMPLATE).render(
            title="EDA Report — dscompanion",
            overview=overview,
            num_cols=num_cols,
            num_rows=num_rows,
            iv_rows=iv_df.to_dict("records"),
            flagged_rows=flagged_rows,
        )
        path.write_text(html, encoding="utf-8")
        logger.info("EDA report saved → %s", path)
        return path

    def to_databricks_display(self) -> None:
        """Render and display the EDA report inline in a Databricks notebook, or write
        it to a local HTML file outside Databricks.

        When running inside a Databricks notebook (detected via
        ``dscompanion.utils.validators.is_databricks``), the report is first
        written to ``/tmp/eda_report.html`` and then rendered inline using
        the Databricks built-in ``displayHTML`` function.  When running
        outside Databricks the report is written to ``eda_report.html`` in
        the current working directory via ``to_html`` as a fallback.

        Args:
            None

        Returns:
            None

        Raises:
            RuntimeError: If ``run_all`` has not been called yet.
        """
        self._check_run()
        if is_databricks():
            # A uniquely-named tempfile.NamedTemporaryFile, not a fixed
            # "/tmp/eda_report.html" path -- Databricks clusters can run multiple
            # users' notebooks concurrently, and a predictable shared-/tmp filename
            # is a symlink/race-condition risk (Bandit B108, a genuine finding here,
            # not a false positive). Cleaned up afterward either way.
            with tempfile.NamedTemporaryFile(suffix=".html", delete=False) as tmp_file:
                tmp = Path(tmp_file.name)
            try:
                self.to_html(tmp)
                html = tmp.read_text()
                displayHTML(html)  # noqa: F821  # Databricks built-in
            finally:
                tmp.unlink(missing_ok=True)
        else:
            self.to_html("eda_report.html")

    def flagged_features(self) -> dict[str, list[str]]:
        """Return a dictionary grouping feature names by their data quality issue category.

        Aggregates flags from all three analysers.  ``constant`` and
        ``high_missing`` originate from the univariate analyser.  ``low_iv``
        is derived from the bivariate IV table using ``settings.iv_threshold``
        as the cutoff.  ``multicollinear`` comes from the multivariate
        analyser's VIF computation.

        Args:
            None

        Returns:
            dict[str, list[str]]: A dictionary with four keys — ``"constant"``
            (features with zero or one unique value), ``"high_missing"``
            (features with more than 30 % null values), ``"low_iv"`` (features
            whose IV falls below ``settings.iv_threshold``), and
            ``"multicollinear"`` (features whose VIF exceeds
            ``settings.vif_threshold``).  Any list may be empty when no
            features fall into that category.

        Raises:
            RuntimeError: If ``run_all`` has not been called yet.
        """
        self._check_run()
        issues = self._uni.flag_issues()
        iv_df = self._bi.iv_table()
        mc = self._multi.flag_multicollinearity()

        return {
            "constant": issues.loc[issues["constant"], "feature"].tolist(),
            "high_missing": issues.loc[issues["high_missing"], "feature"].tolist(),
            "low_iv": iv_df.loc[iv_df["iv"] < settings.iv_threshold, "feature"].tolist(),
            "multicollinear": mc,
        }

    @property
    def recommended_drops(self) -> list[str]:
        """Return a sorted list of column names that are safe to drop based on
        constancy, near-zero variance, and low IV.

        Combines three sources: features flagged as constant by the univariate
        analyser, features with IV below ``settings.iv_threshold`` from the
        bivariate analyser, and numeric features with near-zero variance
        (``near_zero_variance_flag=True``) from the numeric summary.  The union
        of these three sets is returned as a sorted list, so the result is
        deterministic regardless of insertion order.

        Args:
            None

        Returns:
            list[str]: Sorted list of column names recommended for removal.
            Returns an empty list when no features meet any of the three
            criteria.

        Raises:
            RuntimeError: If ``run_all`` has not been called yet.
        """
        self._check_run()
        flagged = self.flagged_features()
        drops = set(flagged["constant"]) | set(flagged["low_iv"])
        # Add near-zero variance
        num_summary = self._uni.numeric_summary()
        if len(num_summary) > 0:
            nzv = num_summary.loc[num_summary["near_zero_variance_flag"], "feature"].tolist()
            drops.update(nzv)
        return sorted(drops)

    def recommended_drops_with_reasons(self) -> dict[str, list[str]]:
        """Return ``recommended_drops``'s same column set, with each column's reason(s) attached.

        Same three sources as ``recommended_drops`` — constant, near-zero
        variance, low IV — but returned as a mapping so a caller (e.g. the
        Interactive-mode Step 5 UI) can show *why* a column is suggested for
        removal, not just that it is.

        Args:
            None

        Returns:
            dict[str, list[str]]: Column name -> sorted list of reasons
            drawn from ``{"constant", "near_zero_variance", "low_iv"}``.
            Sorted by column name; a column may have more than one reason.
            Returns an empty dict when no features meet any criterion.

        Raises:
            RuntimeError: If ``run_all`` has not been called yet.
        """
        self._check_run()
        flagged = self.flagged_features()
        num_summary = self._uni.numeric_summary()
        nzv_cols = (
            set(num_summary.loc[num_summary["near_zero_variance_flag"], "feature"])
            if len(num_summary) > 0
            else set()
        )

        reasons: dict[str, set[str]] = {}
        for col in flagged["constant"]:
            reasons.setdefault(col, set()).add("constant")
        for col in nzv_cols:
            reasons.setdefault(col, set()).add("near_zero_variance")
        for col in flagged["low_iv"]:
            reasons.setdefault(col, set()).add("low_iv")

        return {col: sorted(reasons[col]) for col in sorted(reasons)}

    def iv_table(self) -> pd.DataFrame:
        """Return the bivariate Information Value table, sorted by descending IV.

        Thin public delegate over the fitted ``BivariateAnalyser``, exposing
        per-feature predictive power so callers (e.g. ``ModelCard``) don't
        need to reach into the private ``_bi`` attribute.

        Args:
            None

        Returns:
            pd.DataFrame: One row per feature, columns ``feature``, ``iv``,
            ``n_bins``, ``predictive_power``, sorted by ``iv`` descending
            (the underlying ``BivariateAnalyser.iv_table()`` is pre-sorted).

        Raises:
            RuntimeError: If ``run_all`` has not been called yet.
        """
        self._check_run()
        return self._bi.iv_table()

    def target_rate_by_bin(self, feature: str, n_bins: int = 0) -> pd.DataFrame:
        """Return the observed target rate for each WoE bin of a single feature.

        Thin public delegate over the fitted ``BivariateAnalyser``.

        Args:
            feature (str): Name of a column in the training DataFrame.
            n_bins (int): Quantile bins for numeric features. A value of
                ``0`` delegates to ``settings.default_iv_bins``.

        Returns:
            pd.DataFrame: One row per bin, columns ``bin_label``, ``count``,
            ``target_rate``. See ``BivariateAnalyser.target_rate_by_bin``
            for the full contract.

        Raises:
            RuntimeError: If ``run_all`` has not been called yet.
            KeyError: If ``feature`` is not a column in the training DataFrame.
        """
        self._check_run()
        return self._bi.target_rate_by_bin(feature, n_bins)

    def target_rate_by_bin_chart(self, feature: str, n_bins: int = 0) -> go.Figure:
        """Render a bar chart of the observed target rate across a single feature's WoE bins.

        Thin public delegate over the fitted ``BivariateAnalyser``.

        Args:
            feature (str): Name of a column in the training DataFrame.
            n_bins (int): Quantile bins for numeric features. A value of
                ``0`` delegates to ``settings.default_iv_bins``.

        Returns:
            plotly.graph_objects.Figure: See
            ``BivariateAnalyser.target_rate_by_bin_chart`` for the full
            contract.

        Raises:
            RuntimeError: If ``run_all`` has not been called yet.
            KeyError: If ``feature`` is not a column in the training DataFrame.
        """
        self._check_run()
        return self._bi.target_rate_by_bin_chart(feature, n_bins)

    def numeric_summary(self) -> pd.DataFrame:
        """Return the univariate numeric summary table.

        Thin public delegate over the fitted ``UnivariateAnalyser``.

        Args:
            None

        Returns:
            pd.DataFrame: See ``UnivariateAnalyser.numeric_summary`` for the
            full column schema (count, missing_pct, mean, std, percentiles,
            skewness, outlier rates, flags).

        Raises:
            RuntimeError: If ``run_all`` has not been called yet.
        """
        self._check_run()
        return self._uni.numeric_summary()

    def categorical_summary(self) -> pd.DataFrame:
        """Return the univariate categorical summary table.

        Thin public delegate over the fitted ``UnivariateAnalyser``.

        Args:
            None

        Returns:
            pd.DataFrame: See ``UnivariateAnalyser.categorical_summary`` for
            the full column schema (count, missing_pct, n_unique, top_value,
            top_freq, cardinality_flag).

        Raises:
            RuntimeError: If ``run_all`` has not been called yet.
        """
        self._check_run()
        return self._uni.categorical_summary()

    def datetime_summary(self) -> pd.DataFrame:
        """Return the univariate datetime summary table.

        Thin public delegate over the fitted ``UnivariateAnalyser``. Scope
        is limited to columns already typed ``datetime64`` at fit time.

        Args:
            None

        Returns:
            pd.DataFrame: See ``UnivariateAnalyser.datetime_summary`` for the
            full column schema (count, missing_pct, n_unique, min, max).

        Raises:
            RuntimeError: If ``run_all`` has not been called yet.
        """
        self._check_run()
        return self._uni.datetime_summary()

    def boolean_summary(self) -> pd.DataFrame:
        """Return the univariate boolean summary table.

        Thin public delegate over the fitted ``UnivariateAnalyser``.

        Args:
            None

        Returns:
            pd.DataFrame: See ``UnivariateAnalyser.boolean_summary`` for the
            full column schema (count, missing_pct, n_true, n_false,
            pct_true).

        Raises:
            RuntimeError: If ``run_all`` has not been called yet.
        """
        self._check_run()
        return self._uni.boolean_summary()

    def threshold_guide(self) -> pd.DataFrame:
        """Return percentile distributions of null rate, variance, and CV across all columns.

        Thin public delegate over the fitted ``UnivariateAnalyser``.

        Args:
            None

        Returns:
            pd.DataFrame: See ``UnivariateAnalyser.threshold_guide`` for the
            full column schema (metric, p10, p25, p50, p75, p90, p95, p99).

        Raises:
            RuntimeError: If ``run_all`` has not been called yet.
        """
        self._check_run()
        return self._uni.threshold_guide()

    def plot_distributions(self, top_n: int = 20) -> list[go.Figure]:
        """Return one Plotly distribution figure per feature, up to ``top_n``.

        Thin public delegate over the fitted ``UnivariateAnalyser``.

        Args:
            top_n (int): Maximum number of features to include. Defaults to
                ``20``.

        Returns:
            list[plotly.graph_objects.Figure]: One themed histogram (numeric)
            or bar chart (categorical) per feature, in column order.

        Raises:
            RuntimeError: If ``run_all`` has not been called yet.
        """
        self._check_run()
        return self._uni.plot_distributions(top_n=top_n)

    def numeric_distribution_with_kde(self, col: str, exclude_outliers: bool = False) -> go.Figure:
        """Return one numeric column's histogram with a fitted KDE curve overlaid.

        Thin public delegate over the fitted ``UnivariateAnalyser``.

        Args:
            col (str): Numeric column name, as it appears in ``train_X``.
            exclude_outliers (bool): When ``True``, trims to the P5-P95
                (by default) quantile range before charting. See
                ``UnivariateAnalyser.numeric_distribution_with_kde`` for
                the full contract. Defaults to ``False``.

        Returns:
            plotly.graph_objects.Figure: See
            ``UnivariateAnalyser.numeric_distribution_with_kde`` for the
            full contract, including the empty-figure case for an absent
            or non-numeric column.

        Raises:
            RuntimeError: If ``run_all`` has not been called yet.
        """
        self._check_run()
        return self._uni.numeric_distribution_with_kde(col, exclude_outliers=exclude_outliers)

    def numeric_clean_series(self, col: str) -> pd.Series:
        """Return the dropna'd values for one numeric column.

        Thin public delegate over the fitted ``UnivariateAnalyser``.

        Args:
            col (str): Numeric column name, as it appears in ``train_X``.

        Returns:
            pd.Series: ``train_X[col]`` with missing values removed.
            Returns an empty ``pd.Series`` if ``col`` is not present.

        Raises:
            RuntimeError: If ``run_all`` has not been called yet.
        """
        self._check_run()
        return self._uni.numeric_clean_series(col)

    def categorical_value_counts(self, col: str, top_n: int = 0) -> pd.Series:
        """Return the top-N most frequent values for one categorical column.

        Thin public delegate over the fitted ``UnivariateAnalyser``.

        Args:
            col (str): Categorical column name, as it appears in
                ``train_X``.
            top_n (int): Number of most frequent values to keep. A value
                of ``0`` delegates to ``settings.eda_top_categorical_values``.
                Defaults to ``0``.

        Returns:
            pd.Series: Value counts in descending order, indexed by
            category value, capped at ``top_n`` entries.

        Raises:
            RuntimeError: If ``run_all`` has not been called yet.
        """
        self._check_run()
        return self._uni.categorical_value_counts(col, top_n=top_n)

    def correlation_heatmap(self) -> go.Figure:
        """Return the bivariate Pearson correlation heatmap.

        Thin public delegate over the fitted ``BivariateAnalyser``.

        Args:
            None

        Returns:
            plotly.graph_objects.Figure: Annotated heatmap, ``RdBu`` colour
            scale centred at zero.

        Raises:
            RuntimeError: If ``run_all`` has not been called yet.
        """
        self._check_run()
        return self._bi.correlation_heatmap()

    def pearson_heatmap(self) -> go.Figure:
        """Return the Pearson correlation heatmap reordered by hierarchical clustering.

        Thin public delegate over the fitted ``MultivariateAnalyser``.

        Args:
            None

        Returns:
            plotly.graph_objects.Figure: Square heatmap with ``RdBu`` colour
            scale, axes ordered by average-linkage dendrogram.

        Raises:
            RuntimeError: If ``run_all`` has not been called yet.
            ValueError: If fewer than two numeric columns were present at fit
                time.
        """
        self._check_run()
        return self._multi.cluster_heatmap()

    def correlation_matrix(self) -> pd.DataFrame:
        """Return the Pearson correlation matrix from the multivariate analyser.

        Thin public delegate over the fitted ``MultivariateAnalyser``.

        Args:
            None

        Returns:
            pd.DataFrame: Square correlation matrix (numeric columns × numeric
            columns).  Values are Pearson ``r`` in ``[-1, 1]``.

        Raises:
            RuntimeError: If ``run_all`` has not been called yet.
        """
        self._check_run()
        return self._multi.correlation_matrix()

    def vif_table(self) -> pd.DataFrame:
        """Return the Variance Inflation Factor table from the multivariate analyser.

        Thin public delegate over the fitted ``MultivariateAnalyser``.

        Args:
            None

        Returns:
            pd.DataFrame: Columns ``feature`` (str), ``vif`` (float), ``flag``
            (bool — ``True`` when VIF exceeds ``settings.vif_threshold``).
            Sorted by VIF descending.

        Raises:
            RuntimeError: If ``run_all`` has not been called yet.
        """
        self._check_run()
        return self._multi.vif_table()

    def cramers_v_table(self) -> pd.DataFrame:
        """Return Cramér's V association between every categorical column pair.

        Thin public delegate over the fitted ``MultivariateAnalyser``.

        Args:
            None

        Returns:
            pd.DataFrame: Columns ``col_a`` (str), ``col_b`` (str),
            ``cramers_v`` (float in ``[0, 1]``).  Sorted by Cramér's V
            descending.  Empty DataFrame when fewer than two categorical
            columns were present at fit time.

        Raises:
            RuntimeError: If ``run_all`` has not been called yet.
        """
        self._check_run()
        return self._multi.cramers_v_table()

    def interaction_plots(self) -> list[go.Figure]:
        """Return pairwise numeric-feature interaction plots.

        Thin public delegate over the fitted ``BivariateAnalyser``.

        Args:
            None

        Returns:
            list[plotly.graph_objects.Figure]: See
            ``BivariateAnalyser.interaction_plots`` for the column-cap,
            IV-ranking, and scatter/hexbin-switch behaviour.

        Raises:
            RuntimeError: If ``run_all`` has not been called yet.
        """
        self._check_run()
        return self._bi.interaction_plots()

    def interaction_columns(self) -> list[str]:
        """Return the numeric columns considered for pairwise interaction plots.

        Thin public delegate over the fitted ``BivariateAnalyser``. Lets a
        consumer (e.g. an Excel exporter) build its own per-pair charts
        from the same column selection ``interaction_plots()`` uses,
        without duplicating the IV-ranked capping logic.

        Args:
            None

        Returns:
            list[str]: See ``BivariateAnalyser.interaction_columns``.

        Raises:
            RuntimeError: If ``run_all`` has not been called yet.
        """
        self._check_run()
        return self._bi.interaction_columns()

    def export_charts(
        self,
        output_dir: str | Path,
        format: str = "png",
        dpi: int = 0,
        bivariate_top_n: int = 0,
        bivariate_clip_lower_pct: float = 0.05,
        bivariate_clip_upper_pct: float = 0.05,
        numeric_categorical_style: str = "auto",
        numeric_interaction_trend_line: str = "loess",
        numeric_interaction_trend_poly_degree: int = 2,
        use_target_hue: bool = False,
    ) -> dict[str, Path]:
        """Save every chart category as standalone image files under ``output_dir``.

        Thin public delegate over ``dscompanion.eda.chart_export.export_charts`` —
        see that module's docstring for why this renders matplotlib/seaborn
        figures directly (built from this report's own data-accessor
        methods) rather than exporting the Plotly figures ``plot_distributions()``
        etc. already return, which would require the optional ``kaleido``
        package.

        Args:
            output_dir (str | Path): Root directory for the exported charts.
                Populated with ``univariate/{numeric,categorical}/``,
                ``bivariate/``, ``multivariate/`` (plus
                ``multivariate/interactions/`` when applicable), and
                ``missingness/`` subdirectories.
            format (str): ``"png"`` (default) or ``"svg"``.
            dpi (int): PNG pixel density; ``0`` uses
                ``settings.eda_chart_export_dpi``. Ignored for SVG.
            bivariate_top_n (int): Max features to export bivariate charts
                for, ranked by IV; ``0`` uses
                ``settings.eda_bivariate_chart_top_n``.
            bivariate_clip_lower_pct (float): Lower-tail fraction clipped
                from a numeric feature before binning it for its bivariate
                chart. Has no effect on categorical features. Defaults to
                ``0.05``.
            bivariate_clip_upper_pct (float): Upper-tail fraction clipped
                before the same binning. Defaults to ``0.05``.
            numeric_categorical_style (str): Chart style for
                numeric×categorical interaction pairs -- one of ``"auto"``,
                ``"box"``, ``"violin"``, ``"strip"``, ``"mean_errorbar"``,
                ``"kde"``. ``"auto"`` (default) adaptively resolves a single
                style per pair based on category count and average rows per
                category.
            numeric_interaction_trend_line (str): Trend-line overlay for
                numeric×numeric scatter/hexbin charts (raw/clipped variants
                only) -- one of ``"none"``, ``"linear"``, ``"loess"``,
                ``"polynomial"``. Defaults to ``"loess"``.
            numeric_interaction_trend_poly_degree (int): Polynomial degree
                used only when
                ``numeric_interaction_trend_line="polynomial"``. Defaults to
                ``2``.
            use_target_hue (bool): Color numeric×numeric scatter points
                (raw/clipped variants) and numeric×categorical
                box/violin/strip charts by the target class. Only applied
                when the target is binary (``train_y.nunique() == 2``) --
                silently ignored otherwise. Defaults to ``False``.

        Returns:
            dict[str, Path]: Maps a category-relative key to the absolute
            path written; every value exists on disk.

        Raises:
            RuntimeError: If ``run_all`` has not been called yet.
            ValueError: If ``format`` is not ``"png"`` or ``"svg"``, or if
                ``numeric_categorical_style`` is not a recognized style.
        """
        from dscompanion.eda.chart_export import export_charts as _export_charts

        return _export_charts(
            self,
            output_dir,
            format=format,
            dpi=dpi,
            bivariate_top_n=bivariate_top_n,
            bivariate_clip_lower_pct=bivariate_clip_lower_pct,
            bivariate_clip_upper_pct=bivariate_clip_upper_pct,
            numeric_categorical_style=numeric_categorical_style,
            numeric_interaction_trend_line=numeric_interaction_trend_line,
            numeric_interaction_trend_poly_degree=numeric_interaction_trend_poly_degree,
            use_target_hue=use_target_hue,
        )

    def extreme_values(self, n: int = 0) -> dict[str, dict[str, list]]:
        """Return the smallest and largest raw values for every numeric feature.

        Thin public delegate over the fitted ``UnivariateAnalyser``.

        Args:
            n (int): Number of extreme values per tail.  A value of ``0``
                delegates to the threshold set at construction (itself
                falling back to ``settings.eda_extreme_values_n``).

        Returns:
            dict[str, dict[str, list]]: See
            ``UnivariateAnalyser.extreme_values`` for the full schema.

        Raises:
            RuntimeError: If ``run_all`` has not been called yet.
        """
        self._check_run()
        return self._uni.extreme_values(n=n or self._extreme_values_n)

    def value_counts(self, feature: str, top_n: int = 0) -> pd.DataFrame:
        """Return the full (or top-N) value-frequency table for a single feature.

        Thin public delegate over the fitted ``UnivariateAnalyser``. Works
        for any column dtype (numeric or categorical), unlike
        ``extreme_values()`` (numeric-only).

        Args:
            feature (str): Column name to compute value counts for.
            top_n (int): Maximum number of distinct values returned. A value
                of ``0`` returns every distinct value.

        Returns:
            pd.DataFrame: See ``UnivariateAnalyser.value_counts`` for the
            full schema.

        Raises:
            RuntimeError: If ``run_all`` has not been called yet.
            KeyError: If ``feature`` is not a column in the fitted data.
        """
        self._check_run()
        return self._uni.value_counts(feature, top_n=top_n)

    def correlation_table(self) -> pd.DataFrame:
        """Return the raw Pearson correlation matrix as a DataFrame.

        Thin public delegate exposing ``BivariateAnalyser``'s already-fitted
        correlation matrix — no recomputation. Pairs with
        ``correlation_heatmap()`` for a raw-table-alongside-the-heatmap view.

        Args:
            None

        Returns:
            pd.DataFrame: Square correlation matrix, numeric columns only,
            index and columns both feature names. Empty DataFrame if fewer
            than 2 numeric columns were present at fit time.

        Raises:
            RuntimeError: If ``run_all`` has not been called yet.
        """
        self._check_run()
        return self._bi.correlation_matrix()

    def overview_summary(self) -> dict[str, Any]:
        """Return high-level dataset statistics: rows, columns, missing cells, duplicate rows.

        Computed directly from ``split.train_X`` — independent of which
        individual analysers ran, so it is always available once
        ``run_all()`` has been called.

        Args:
            None

        Returns:
            dict[str, Any]: ``{"total_rows": int, "total_columns": int,
            "total_missing": int, "missing_pct": float, "duplicate_rows":
            int, "duplicate_pct": float}``.

        Raises:
            RuntimeError: If ``run_all`` has not been called yet.
        """
        self._check_run()
        df = self._split.train_X
        total_rows, total_cols = df.shape
        total_cells = total_rows * total_cols
        total_missing = int(df.isna().sum().sum())
        duplicate_rows = int(df.duplicated().sum())
        return {
            "total_rows": total_rows,
            "total_columns": total_cols,
            "total_missing": total_missing,
            "missing_pct": round(100 * total_missing / max(total_cells, 1), 2),
            "duplicate_rows": duplicate_rows,
            "duplicate_pct": round(100 * duplicate_rows / max(total_rows, 1), 2),
        }

    def missing_values_chart(self) -> go.Figure:
        """Build a Plotly bar chart of missing-value % across every feature, sorted descending.

        Combines the numeric and categorical summary tables so every column
        is visible in one chart, rather than requiring a reviewer to scan
        two separate tables to find the worst offenders.

        Args:
            None

        Returns:
            plotly.graph_objects.Figure: Themed bar chart, ``missing %`` on
            the y-axis, features sorted descending by missing rate.  An
            empty figure (no bars) when there are no columns.

        Raises:
            RuntimeError: If ``run_all`` has not been called yet.
        """
        self._check_run()
        num_df = self._uni.numeric_summary()[["feature", "missing_pct"]]
        cat_df = self._uni.categorical_summary()[["feature", "missing_pct"]]
        combined = pd.concat([num_df, cat_df], ignore_index=True)
        combined = combined.sort_values("missing_pct", ascending=False)
        fig = go.Figure(
            go.Bar(
                x=combined["feature"],
                y=combined["missing_pct"] * 100,
                marker_color="#c0392b",
            )
        )
        fig.update_layout(
            title="Missing Values by Feature", xaxis_title="feature", yaxis_title="missing %"
        )
        return apply_dscompanion_theme(fig)

    def missing_matrix(self) -> pd.DataFrame:
        """Return the boolean per-row, per-column missingness matrix.

        Thin public delegate over the fitted ``MissingnessAnalyser``.

        Args:
            None

        Returns:
            pd.DataFrame: See ``MissingnessAnalyser.nullity_matrix`` —
            ``True`` where the original value was null, row-subsampled to
            ``settings.eda_missing_matrix_max_rows``.

        Raises:
            RuntimeError: If ``run_all`` has not been called yet.
        """
        self._check_run()
        return self._missing.nullity_matrix()

    def missing_correlation(self) -> pd.DataFrame:
        """Return the phi-coefficient correlation matrix between columns' missingness indicators.

        Thin public delegate over the fitted ``MissingnessAnalyser``.

        Args:
            None

        Returns:
            pd.DataFrame: See ``MissingnessAnalyser.nullity_correlation`` —
            restricted to columns with partial missingness.

        Raises:
            RuntimeError: If ``run_all`` has not been called yet.
        """
        self._check_run()
        return self._missing.nullity_correlation()

    def missing_matrix_chart(self) -> go.Figure:
        """Return a Plotly heatmap of the boolean missingness matrix.

        Thin public delegate over the fitted ``MissingnessAnalyser``.

        Args:
            None

        Returns:
            plotly.graph_objects.Figure: See
            ``MissingnessAnalyser.nullity_matrix_chart``.

        Raises:
            RuntimeError: If ``run_all`` has not been called yet.
        """
        self._check_run()
        return self._missing.nullity_matrix_chart()

    def missing_correlation_heatmap(self) -> go.Figure:
        """Return a Plotly heatmap of the nullity correlation matrix.

        Thin public delegate over the fitted ``MissingnessAnalyser``.

        Args:
            None

        Returns:
            plotly.graph_objects.Figure: See
            ``MissingnessAnalyser.nullity_correlation_heatmap``.

        Raises:
            RuntimeError: If ``run_all`` has not been called yet.
        """
        self._check_run()
        return self._missing.nullity_correlation_heatmap()

    def sample_rows(self) -> dict[str, pd.DataFrame]:
        """Return the first and last ``N`` raw training rows, gated behind a compliance opt-in.

        Exposes raw row-level data, which is a materially different risk
        from aggregate statistics in a static HTML report meant to be
        shared with stakeholders — see ``EDAConfig.include_sample_rows``.
        The gate is enforced here (not by the caller) so this method is
        always safe to call regardless of how ``ModelCard`` is wired.

        Args:
            None

        Returns:
            dict[str, pd.DataFrame]: ``{"head": pd.DataFrame, "tail":
            pd.DataFrame}``, each with up to ``settings.eda_sample_n_rows``
            rows from the training data. Both are empty DataFrames (no
            columns) when ``include_sample_rows`` was not enabled at
            ``EDAReport`` construction time.

        Raises:
            RuntimeError: If ``run_all`` has not been called yet.
        """
        self._check_run()
        if not self._include_sample_rows:
            return {"head": pd.DataFrame(), "tail": pd.DataFrame()}
        df = self._split.train_X
        return {"head": df.head(self._sample_n_rows), "tail": df.tail(self._sample_n_rows)}

    def duplicate_row_content(self) -> pd.DataFrame:
        """Return the raw content of duplicated training rows, gated behind a compliance opt-in.

        Exposes raw row-level data — see ``EDAConfig.include_duplicate_row_content``.
        The gate is enforced here (not by the caller), same posture as
        ``sample_rows``. The duplicate row *count* in ``overview_summary()``
        is unaffected by this gate and always reflects the true count.

        Args:
            None

        Returns:
            pd.DataFrame: All rows participating in a duplicate group (i.e.
            ``df.duplicated(keep=False)``), with an added ``_dup_count``
            column (number of rows sharing that exact value combination),
            capped at ``settings.eda_duplicate_rows_max_display`` rows.
            Empty DataFrame (no columns) when ``include_duplicate_row_content``
            was not enabled at ``EDAReport`` construction time, or when there
            are no duplicate rows.

        Raises:
            RuntimeError: If ``run_all`` has not been called yet.
        """
        self._check_run()
        if not self._include_duplicate_row_content:
            return pd.DataFrame()
        df = self._split.train_X
        dup_df = df[df.duplicated(keep=False)].copy()
        if dup_df.empty:
            return dup_df
        cols = list(df.columns)
        dup_df["_dup_count"] = dup_df.groupby(cols, dropna=False)[cols[0]].transform("size")
        return dup_df.head(self._duplicate_rows_max_display)

    def alerts(self) -> dict[str, list[dict[str, str]]]:
        """Return a unified, per-feature list of data-quality alerts.

        Aggregates signals already computed by all three analysers into a
        single rendering-friendly structure — complements (does not
        replace) ``flagged_features()``/``recommended_drops``, which remain
        the programmatic "what to drop" API.  Wires in
        ``BivariateAnalyser.flag_high_correlation()``, which previously had
        no caller anywhere in the reporting layer.

        Args:
            None

        Returns:
            dict[str, list[dict[str, str]]]: Keyed by feature name, each
            value a list of ``{"type": str, "detail": str}`` dicts.
            ``type`` is one of the ``EDAAlert.*`` constants.  Features with
            no alerts are absent from the dict (not present with an empty
            list).

        Raises:
            RuntimeError: If ``run_all`` has not been called yet.
        """
        self._check_run()
        num_df = self._uni.numeric_summary()
        cat_df = self._uni.categorical_summary()
        iv_df = self._bi.iv_table()
        multicollinear = set(self._multi.flag_multicollinearity())
        high_corr = self._bi.flag_high_correlation()

        result: dict[str, list[dict[str, str]]] = {}

        def _add(feature: str, atype: str, detail: str) -> None:
            result.setdefault(feature, []).append({"type": atype, "detail": detail})

        for _, r in num_df.iterrows():
            f = r["feature"]
            if r["missing_pct"] > self._high_missing_threshold:
                _add(f, EDAAlert.HIGH_MISSING, f"{r['missing_pct'] * 100:.1f}% missing")
            if bool(r["constant_flag"]):
                _add(f, EDAAlert.CONSTANT, "zero variance")
            if bool(r["near_zero_variance_flag"]):
                _add(f, EDAAlert.NEAR_ZERO_VARIANCE, "variance below threshold")
            if pd.notna(r["skewness"]) and abs(r["skewness"]) >= self._skewness_alert_threshold:
                _add(f, EDAAlert.SKEWED, f"skewness={r['skewness']:.2f}")
            if r["zero_pct"] >= self._zero_pct_alert_threshold:
                _add(f, EDAAlert.ZEROS, f"{r['zero_pct'] * 100:.1f}% zeros")

        for _, r in cat_df.iterrows():
            f = r["feature"]
            if r["missing_pct"] > self._high_missing_threshold:
                _add(f, EDAAlert.HIGH_MISSING, f"{r['missing_pct'] * 100:.1f}% missing")
            if bool(r["cardinality_flag"]):
                _add(f, EDAAlert.HIGH_CARDINALITY, f"{r['n_unique']} unique values")
            if r["n_unique"] <= 1:
                _add(f, EDAAlert.CONSTANT, "single value")
            imb = r.get("imbalance")
            if imb is not None and pd.notna(imb) and imb >= self._imbalance_alert_threshold:
                _add(f, EDAAlert.IMBALANCED, f"imbalance score={imb:.2f}")

        for _, r in iv_df.iterrows():
            if r["iv"] < settings.iv_threshold:
                _add(r["feature"], EDAAlert.LOW_IV, f"IV={r['iv']:.4f}")

        for f in multicollinear:
            _add(f, EDAAlert.MULTICOLLINEAR, "VIF exceeds threshold")

        for _, r in high_corr.iterrows():
            _add(
                r["feature_a"],
                EDAAlert.HIGH_CORRELATION,
                f"r={r['pearson_r']} with {r['feature_b']}",
            )
            _add(
                r["feature_b"],
                EDAAlert.HIGH_CORRELATION,
                f"r={r['pearson_r']} with {r['feature_a']}",
            )

        return result

    def flag_high_correlation(self) -> pd.DataFrame:
        """Return numeric column pairs whose Pearson correlation exceeds the configured threshold.

        Thin public delegate over the fitted ``BivariateAnalyser``. Only the
        upper triangle of the correlation matrix is inspected to avoid duplicate
        pairs. Threshold is read from ``settings.correlation_threshold``.

        Args:
            None

        Returns:
            pd.DataFrame: Columns ``feature_a`` (str), ``feature_b`` (str),
            ``pearson_r`` (float, rounded). One row per flagged pair.
            Empty DataFrame with those columns when no pair exceeds the
            threshold.

        Raises:
            RuntimeError: If ``run_all`` has not been called yet.
        """
        self._check_run()
        return self._bi.flag_high_correlation()

    def flag_multicollinearity(self) -> list[str]:
        """Return names of numeric features whose VIF exceeds the configured threshold.

        Thin public delegate over the fitted ``MultivariateAnalyser``.
        Threshold is read from ``settings.vif_threshold``.

        Args:
            None

        Returns:
            list[str]: Feature names with VIF above ``settings.vif_threshold``,
            in VIF descending order. Returns an empty list when no feature
            exceeds the threshold.

        Raises:
            RuntimeError: If ``run_all`` has not been called yet.
        """
        self._check_run()
        return self._multi.flag_multicollinearity()

    def text_analysis(
        self,
        top_n_words: int = 0,
        top_n_chars: int = 0,
        include_sample_values: bool | None = None,
    ) -> dict[str, Any]:
        """Return word/character frequency and Unicode breakdown for all categorical columns.

        Thin public delegate over the fitted ``UnivariateAnalyser``. Uses
        instance-level ``_text_analysis_top_n_words`` / ``_text_analysis_top_n_chars``
        when the caller passes ``0``, and the instance-level
        ``_include_text_sample_values`` compliance flag unless overridden.

        Args:
            top_n_words (int): Top-N words per column. A value of ``0``
                delegates to the instance's configured value.
            top_n_chars (int): Top-N characters per column. A value of ``0``
                delegates to the instance's configured value.
            include_sample_values (bool | None): Override the instance-level
                ``include_text_sample_values`` flag. ``None`` uses the
                instance-level value.

        Returns:
            dict[str, Any]: See ``UnivariateAnalyser.text_analysis`` for the
            full per-column schema. Empty dict when no categorical columns
            are present.

        Raises:
            RuntimeError: If ``run_all`` has not been called yet.
        """
        self._check_run()
        return self._uni.text_analysis(
            top_n_words=top_n_words or self._text_analysis_top_n_words,
            top_n_chars=top_n_chars or self._text_analysis_top_n_chars,
            include_sample_values=(
                include_sample_values
                if include_sample_values is not None
                else self._include_text_sample_values
            ),
        )

    def _check_run(self) -> None:
        if self._uni is None:
            raise RuntimeError("Call run_all() before accessing the report.")
